---
title: "Census_Analysis"
format: pdf
editor: visual
---

Link: https://www.census.gov/data/datasets/time-series/demo/cps/cps-asec.html

Read and join house and person data for one year
```{r}
# Load 2020 Data
house_20 <- read.csv("Data/asecpub20csv/hhpub20.csv")
person_20 <- read.csv("Data/asecpub20csv/pppub20.csv")

# Select Vars
person_20 <- person_20 |> select(AGE1,PRDTRACE,PRDASIAN,A_MJOCC,PEIO1COW,PH_SEQ)
house_20 <- house_20 |> select(GEDIV, GEREG,GESTFIPS, HEFAMINC, 
                                H_TYPEBC, H_YEAR, H_MONTH,H_SEQ)

house_person_20 <- person_20 |>
  inner_join(house_20, by = c("PH_SEQ" = "H_SEQ"))
```

Read and join house and person data iteratively for 2019-2024
```{r}
# Read first
  file_path <- paste0("census_data/house_person_", 19, ".csv")
  house_person <- read.csv(file_path)
  
# Range of next years
  years <- 19:24
  
for (year in years) {
  
  file_path <- paste0("census_data/house_person_", year, ".csv")
  second_file <- read.csv(file_path)
  
  house_person <- rbind(house_person, second_file)
}
```
